### ISSUE TITLE
Add new profiles

### ISSUE THREAD

**Issue by nicoguaro** [AntiMicro/antimicro-profiles#1]
I would like to add some profiles. I have created these ones for me:
- Bastion
- Dreamfall
- Brothers: A tale of two sons

Also, I would like to ask you to create a section in the README with the instructions for new profiles.

Thanks,
Nicolas

**Comment by jsbackus** [comment]
@nicoguaro Great! Please send me a pull request. Also a good idea to update the README with instructions. I'll do it when I get a chance. I'll keep this issue open until I do. Thanks!

**Comment by nicoguaro** [comment]
I added the profiles.
